theme:
  active: "8,145,106" # a) current playing song in list & b) selected pane border
  banner: "8,145,106" # the "spotify-tui" banner on launch
  error_border: "222,61,59" # error dialog border
  error_text: "222,61,59" # error message text (e.g. "Spotify API reported error 404")
  hint: "224,175,2" # hint text in errors
  hovered: "40,142,215" # hovered pane border
  playbar_text: "64, 63, 83"
  selected: "224,175,2" # selected pane border
  playbar_progress: "8,145,106" # colour of the filled-in part of the progress bar
  playbar_background: "240,240,240" # background colour of progress bar
  inactive: "64,63,83" # colour of borders of non-selected panes
  text: "64,63,83" # colour of text in panes
