[[themes]]
name = "github"
[themes.palette]
background = "#f4f4f4"
foreground = "#3e3e3e"
black = "#3e3e3e"
red = "#970b16"
green = "#07962a"
yellow = "#c5bb94"
blue = "#003e8a"
magenta = "#e94691"
cyan = "#7cc4df"
white = "#b2b2b2"
bright_black = "#666666"
bright_red = "#de0000"
bright_green = "#7ac895"
bright_yellow = "#d7b600"
bright_blue = "#2e6cba"
bright_magenta = "#f29592"
bright_cyan = "#00c7cb"
bright_white = "#ffffff"
